name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      deployments: write
      id-token: write
      packages: write

    steps:

      - name: Check out project main branch
        uses: actions/checkout@v5
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest

      - name: Trigger Server Update with Watchtower
        run: |
          curl -fSL \
            -H "Authorization: Bearer ${{ secrets.WATCHTOWER_API_TOKEN }}" \
            ${{ vars.WATCHTOWER_ENDPOINT }}
